### ISSUE TITLE
Any way to logout?

### ISSUE THREAD

**Issue by samarthagarwal** [cosmith/cordova-digits#1]
How do I de-authenticated a user/device?

**Comment by cosmith** [comment]
Hi, there's currently no way to do this with the plugin. I'd be happy to look at pull requests though.

**Comment by samarthagarwal** [comment]
Any directions on how to do that? Will clearing localStorage be the way to go?

**Comment by cosmith** [comment]
Apparently there's a method `Digits.getSessionManager().clearActiveSession();` (https://twittercommunity.com/t/how-to-delete-login-session-of-digit/56853)
